version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Build debug APK and release APK
          command: |
            ./gradlew :app:assembleDebug
            ./gradlew :app:assembleDebugAndroidTest
            
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
          environment:
            GCLOUD_SERVICE_KEY: {
  "type": "service_account",
  "project_id": "androiddemo-3edde",
  "private_key_id": "a41a1d6f994d7976c382429f44c61b2dd20019f3",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDUQpU7Lvx74Mew\nQQivJzCbXgqyYkJeMyycWkA73Ei+lbjKNYXFropNRp52NMKrN2Mts8Qy9JJpodcn\ny3VbP1oHbGc1bNdWoyxNzXck8mWILsmhhbqK3WeVJXbSzTQQZyyjHbGxEz5mLECW\nbBWK88nKDMJB81akcQbuiZPMbQg4IDxke5a6BWz4grs2ncqVrTg6WtldOjAWeS+C\nfDY9UDdUB4+gDqNGq3qxb8YVoWaxyOBsF6dusX3xzr9E7OqmrFkyl19rqfRqgsJH\nwy9txXdXZuS1XTaGbGVvTxv7ZMC44fo4XhEicZgRZkxymZoGlGLsAdHzDeW6/akg\nL6N/d/9RAgMBAAECggEATz6yfz+KBOfFNbD6AIZ1l7PS84lKtOePIqpxK8gQopK8\nREYaNNT2jmYsl/4XpZuOnAvu1oVHukcxUAqePFxZDMd0etYxSQevbTal4jXbIS4y\nmeqW2+xQFTdA9u+knfEfEaDu66i/FZ8019PvcQqWTihYSA4EzWzjRSA4/UvBk04L\nOYW3Y9+9bImT5fdye5MBPCRlyBqs0jm7+EpKBGj7A2h1HHF+jhJ65SM2MjQOhQK0\npGdT6yB9qlLNtOZr3wZukbH+0e3qPCnR0ztQczAeYLSaYwxaFg+n6OzVyxUINrJ6\n3N3/IiuT4Fp9ZLxZ8xGgRucJVGfxhubeE9Cs76QFfwKBgQD5ZVNEmsC28f2xdSeQ\nY11FthF8MaAbYpg1aEVpyXosiQs7ZTA/gbWEB/R4MKog7WfIeDNaeakK2Xl5i4Es\nAlqj2Q2+iqJZ8412zHeg3A0UxbdIK02kr1M8dD3TbtG8CuXVBgwBmoeESqm6ssre\nOiU0OmhrS5Ya/gCu+M/TUAWw7wKBgQDZ4YL4z2tzrsyOwlT0umh2u/6jldjxSBxc\nsuqxnk9izsIA7Ptp6Q6qq0e4CSd/rabOVbr1X3+vvrVk8tWgQMhnP5gikSNZYodk\nokCMTyj5pOa2kb5IRtrSmo+OrroVYD5unwv8VG9U7Iz/Uwx+cKHkauiroD2PxWwf\n1CJkw9zTvwKBgQD5PluWj7aT34r0RCpzMerwlYIqBYqGc+W8UmY00CeqxJeWF429\nmksnFbAsQi500+7Jud9Qx4+6iRfO8i35Jq0hXPZQfEq+7RpvJO9VszXbkbGXjbd+\nI75jB6UWXoV7kcSaPf3XyHExNFEmhjMbHy85YDolKRhuB3X1aDKDdFELvwKBgEYf\nEevJtadRhnwbhwQMSjqMXnN/coaU0qvy2R24+YuvRzjNDE0VuKas4TQVniS1Wo3l\ngXoe9hU1p2OJ077zmovAJ9JYK6xEzZZRsbx2bZWKwMXZOghA5YQKQlGFYlYm13D6\ntvzKn9oRF3/E1qyKy0+cKK2zsJxoyVelCjyr3JI5AoGABprdN0aESyfP7OcQ9Blj\nP+M9Pu44vrUPbxOfO0nYwkLHBE6LNUPpuptdZirPbpe5K6h0dzB9XTkCGqD+edMu\ni10zI6VoYbhRNl3i60GWq1ArLRoz7alYXbe85E7hneNht3+HrvCOlwwzt4YrG4Q/\ndkPfxTPCK1awpwto5gYNC/0=\n-----END PRIVATE KEY-----\n",
  "client_email": "gcloud-service-key@androiddemo-3edde.iam.gserviceaccount.com",
  "client_id": "111962189006301624277",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/gcloud-service-key%40androiddemo-3edde.iam.gserviceaccount.com"
}      
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            sudo gcloud --quiet config set project androiddemo-3edde  
            
      - run:
          name: Test with Firebase Test Lab
          command: >
            sudo gcloud firebase test android run \ 
              --app /home/ketan/Downloads/mytaxi-demo.apk \ 
              --results-bucket cloud-test-${GOOGLE_PROJECT_ID}
      - run:
          name: Install gsutil dependency and copy test results data
          command: |
            sudo pip install -U crcmod
            sudo gsutil -m cp -r -U `sudo gsutil ls gs://[BUCKET_NAME]/[OBJECT_NAME] | tail -1` ${CIRCLE_ARTIFACTS}/ | true
